### ISSUE TITLE
Save and Open does not open correct feature sizes

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#114]
Using the save and open options to setup a new project but using a similar previously used composer settings, the grid sizing and feature sizing are incorrect. (i've made sure both were using the same video camera settings 10x)

Number of features, grids, names are all correct though

**Comment by bradmartin333** [comment]
Is the PxPerMicron in the SEYR Panel the same? How about the scaling?

If all looks good, then attach the SEYRdebug.txt here - some weirdness but
don't know if it is host or SEYR.

**Comment by bradmartin333** [comment]
@riversn is this still an issue?

**Comment by riversn** [comment]
It's been mixed, It's done it sometimes, and other times it works fine.

Might have been an older seryup vs using newer seryups. If it happens again, i'll update
