### ISSUE TITLE
Grid Composer Updates

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#116]
Clicking on left grid should highlight the closest grid unit to the cursor.

When we have a big grid of 25x25 or more it's a pain to press the up/down button to change which unit in the grid is being displayed on the right side. Can we just click it and it would highlight that unit?

**Comment by riversn** [comment]
Also, at the start when you click and make a 10x10 grid unit by default, can we just center the unit on the cursor instead of doing the top left corner? People have asked :)

**Comment by bradmartin333** [comment]
- [ ] Hit test for selecting active R/C
- [ ] Centered tile on new project
