### ISSUE TITLE
Seyr Compresses and saves (duplicates) previous run

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#117]
Not sure if you've fixed this in the latest SEYR or not, but when you press run in SEYR, the program compresses the previous run and saves a duplicate seryup.

**Comment by bradmartin333** [comment]
This is entirely controlled by the host program

I was being extra super careful at first - but with the deletion of 1 or 2 lines in the host program you will have SEYRUPs generated only when a run is completed (green eye) and when the user manually creates one
