### ISSUE TITLE
Button to turn composer pattern rec off

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#118]
When a pattern follower is set, sometimes composer will open with the pattern follower engaged and it's annoying. A quick button to 'turn off and back on' once a pattern has been made would be nice.

The issue is that if you reopen the composer and it does a pattern follow, if you recenter the grid it'll be off when you do a run.

**Comment by bradmartin333** [comment]
Ok - I think this is how it works now (First time using this cool framework called `mermaid` to make diagrams)

```mermaid
flowchart TD;
    nextImage-.->goodPatternFollow;
    nextImage-.->nullPatternFollow;
    goodPatternFollow-->updateOffset;
    nullPatternFollow-->stored;
    updateOffset-->stored;
    stored-->nextImage;
    stored-->composer;
    nullOffset--Initial Value-->stored;
    stored:::someclass;
    classDef someclass fill:#f96;
    nullOffset:::nullclass;
    classDef nullclass fill:#f69;
```

And you would like it to be like this?

```mermaid
flowchart TD;
    nextImage-.->goodPatternFollow;
    nextImage-.->nullPatternFollow;
    goodPatternFollow-->updateOffset;
    nullPatternFollow-->stored;
    updateOffset-->stored;
    stored-->nextImage;
    stored-.-toggle;
    nullOffset--Initial Value-->stored;
    stored:::someclass;
    classDef someclass fill:#f96;
    nullOffset:::nullclass;
    classDef nullclass fill:#f69;
    nullOffset-.-toggle;
    toggle-->composer;
```

**Comment by bradmartin333** [comment]
@riversn does this look correct?

**Comment by riversn** [comment]
Yeah

**Comment by bradmartin333** [comment]
I think I fixed this? I noticed that the `Feature Layout` in the composer always uses the follower pattern offset, but the `Feature Grid` never does. So, now the `Feature Grid` always uses the follower pattern offset. I think this removes the confusion as the composer will now always reflect the viewer and any grid location changes will be in relation to what you are looking at, not what you are looking at +/- the possible follower pattern. That being said - I might have missed the nail - we'll see.

**Comment by bradmartin333** [comment]
one annoying thing I noticed is teaching a new pattern after successful pattern rec - best to do it on the very first image of the population and then you don't run into that issue

**Comment by riversn** [comment]
I want the composer to never shift the grid position, force pattern in the viewer, or running should be the only time the pattern rec gets applied to a grid

**Comment by bradmartin333** [comment]
Yeah I did the opposite - I can flip it just as easily.

But right now, If PR happens and then you stop the run and open composer, you can edit the grid and feature and those changes will be consistent with null & future PR offsets.

If I do the opposite, you would basically have to go to back to the image you set up the PR on for the grid to line up again.

In the version you have now - it is half and half - the grid never gets the PR and the feature always gets the PR. Whichever you decide (always use or never use) they will both at least be the same.

**Comment by riversn** [comment]
maybe always on is fine if there's a manual on and off pattern rec button.

**Comment by bradmartin333** [comment]
okay - moved to #119
