### ISSUE TITLE
Fresh Eyes Feedback

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#122]
Had some completely fresh eyes trying to use SEYR.

Biggest thing:

- "Why can I not click and drag the boxes? It would be so much easier"
    On Left side grid: single Clicking inside of the box should highlight it on the right screen. Corners should be draggable (maybe only top left/bottom right).     Click, hold, and dragging should be able to move the box position. or clicking the edge of the box should be able to drag and move it too.
- The yellow 'no images' page wasn't clear enough, user didn't know what it meant - probably need some text on the picture saying "no images are being saved, are you sure" or something?
- "Current layout is very easy and intuitive once you know what you're trying to do" - great feedback!
- "Img" unit inspect boxes shouldn't be showing up in the viewer because we don't really care about the img pass/fail rate and seeing the larger img box fail a unit when the LEDs are actually there is very confusing for a new user
        -     Haven't tested if this is the case on the latest seyr using the make img button, cuz we are still running the older ver. will test next week, got them to add to the latest xferprint

**Comment by riversn** [comment]
Finally got them to add the latest seyr/gridmaker to the next version of xferprint, it's going live on monday... so will actually get to use those quality of life improvements i've been waiting on

**Comment by riversn** [comment]
"apply angle/deskew" should just be next to the angle numbers... new users don't understand it or know it was there. and they didn't understand that changing the angle was even worthwhile. 

"Auto Calc Angle" button should just be to the right of the angle values instead of under tools.

"Find Angle" idk the good name

**Comment by bradmartin333** [comment]
> "apply angle/deskew" should just be next to the angle numbers... new users don't understand it or know it was there. and they didn't understand that changing the angle was even worthwhile.
> 
> "Auto Calc Angle" button should just be to the right of the angle values instead of under tools.
> 
> "Find Angle" idk the good name

Added as #123

**Comment by bradmartin333** [comment]
> * The yellow 'no images' page wasn't clear enough, user didn't know what it meant - probably need some text on the picture saying "no images are being saved, are you sure" or something?

I have some text in the bar at the bottom:

![image](https://user-images.githubusercontent.com/19335151/182884121-4fd460dd-e5b4-45dc-a16f-30f46f5e2985.png)

But I will make the image with an arrow that points to that in #124

**Comment by bradmartin333** [comment]
> * Clicking inside of the box should highlight it on the right screen.

I think this one is done 👍

> * Corners should be draggable (maybe only top left/bottom right).     Click, hold, and dragging should be able to move the box position. or clicking the edge of the box should be able to drag and move it too.

I can do this in https://github.com/bradmartin333/LI4 but it is not really practical for SEYR (you would always be frustrated with edge cases due to scaling)

**Comment by bradmartin333** [comment]
> * "Img" unit inspect boxes shouldn't be showing up in the viewer because we don't really care about the img pass/fail rate and seeing the larger img box fail a unit when the LEDs are actually there is very confusing for a new user

Opened in #125

**Comment by bradmartin333** [comment]
> Had some completely fresh eyes trying to use SEYR.

That's great to hear! Also, great feedback - I can do most of these easily, but the click and drag stuff won't perform well. I am planning to make LI4 the successor to SEYR and those sorts of things will all be built in as well as database integration. On another note, the database testing with SEYR went well. If it becomes imperative I can revisit that - otherwise, I will crawl along with LI4.

**Comment by riversn** [comment]
sounds good, we aren't desperate for anything database wise because the system we have now just works (why change if it just works)?

**Comment by bradmartin333** [comment]
love to hear it - just finished making those changes I took from this post
