### ISSUE TITLE
More user feedback for click grid functions

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#126]
when clicking to 'move' or place the grid box on the left side, it is correctly centering around the courser, but it's just barely misaligned.
 (cntl + G)
It's almost as if it's being placed to the center of the mouse, not the point of the mouse.
Maybe backing off the offset by 1 px would do it. 

![image](https://user-images.githubusercontent.com/101815602/184000502-c589f8a1-ee2f-460e-b34e-e2f35a03f086.png)

**Comment by bradmartin333** [comment]
before, it used the top left corner and didn't have the issue. now, it uses the "center" but the center has to be a pixel and, depending on your scaling, it could seem like it is one pixel off for edge cases

**Comment by bradmartin333** [comment]
tried `floor`, `ceiling`, +1 and -1 and they all have the same edge case issue (there just aren't that many pixels in the tile)

**Comment by riversn** [comment]
It's actually perfect on the right screen, but on the left grid it's slightly off... idk, maybe it's just me

**Comment by bradmartin333** [comment]
left = grid, right = feature

the left is perfect and the right is slightly off, correct?

if so, then it is not just you

**Comment by riversn** [comment]
No, it's opposite, the inspection viewer on the right is correct.

The left side grid array is slightly off

**Comment by bradmartin333** [comment]
https://user-images.githubusercontent.com/19335151/184418757-5d8b8d2c-449f-4b63-88d1-238959954553.mp4

left feels good, right is understandably off (but that is what I want to make "feel" better without actually changing the outcome)

**Comment by bradmartin333** [comment]
I did a good amount of testing here (I even dabbled with click and drag/resize functions), but I can't seem to make this "feel" better without redoing the entire form.

**Comment by riversn** [comment]
Well... it's good enough. If it can't be easily fixed then oh well
