### ISSUE TITLE
Host UI strict locations for Grid Maker

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#127]
What's this? I tried reteaching target A-B, restarting seyr, restarting xferprint, it wouldn't let me set the origin and it wouldn't let me click run, or tools buttons from the seyr menu.

![image](https://user-images.githubusercontent.com/101815602/184229817-d007cc9e-19ec-4f3f-bc7c-b756410499b8.png)

**Comment by bradmartin333** [comment]
This is a bit complicated - You can check the EventLog, but essentially, your recipe origins indicate that your stamp head is not over either the target or the source (The only 2 valid locations that Grid Maker can use - unless you are using Stamp/Camera Mode as that is special). I am guessing you made a special recipe just for metro?

In any case, this is purely a SEYR Control Panel driven message box and is likely resolvable with the correct button clicks in the main XferPrint UI.

We can set up a teams call maybe so that it is on the books/screen shareable? I dunno the best way - but someone on the SW could help you if you direct them to the MakePoints() function of SEYRpanel.cs within the XferPrint Utilities

**Comment by riversn** [comment]
Well... if it happens again we'll see... totally locks you out of using seyr though

**Comment by riversn** [comment]
I think this is actually two separate issues. I think there was a problem with xferprint thinking it was in low mag mode, when it wasn't and therefore the chuck position was messed up. I haven't been able to replicate that in particular.

The other issue is that for some reason the current SEYR will totally bug out and the Run/Tool buttons at the top bar become unclickable. The origin is set, the composer is set, reopening seyr doesn't fix, but closing xferprint and then opening seyr again allowed the run buttons to clicked.

Not sure what's bugging it out, the last time it happened this morning was a normal setup -> navigate in high mag to starting position. -> Save origin. -> Open previously used directory (so I can easily copy over composer settings). -> Save as and open new dir -> open gridmaker, load a saved gridmaker file, validate and close -> open composer and tweak angle, adjust threshold etc... -> save composer and at this point the run/tool buttons are unclickable.

in this scenario, composer, gridmaker, and origin is setup but the run/tool buttons are locked out.

**Comment by bradmartin333** [comment]
GridMaker is actually the culprit - it cannot provide you points without valid AB points

Originally I forced to user to reteach AB just for GridMaker, but decided users would enjoy using the existing AB from the source and target chucks

That manual option could be easily added back into the `SEYRpanel` with some buttons and remapping of the implementation of GridMaker (in essence, it is a XferSuite request)

**Comment by bradmartin333** [comment]
Ah okay - yeah that is annoying, but is purely a `SEYRpanel` bug - CLOSING AGAIN lollll 😇

**Comment by bradmartin333** [comment]
important to make the distinction between `SEYRpanel` and `SEYR` - I don't have any access to what you see in `SEYRpanel`, but I could fix them - this ties in with #128

**Comment by riversn** [comment]
Figured this one out, making a note for whoever wants to fix it in the future.

There is an issue with the 'Go-TO' buttons. If you open xferprint and setup Stamp A-B, then open SeyrPanel, it will work.... but if you Stamp A-B and press 'Stamp A GOTO, or B GOTO' then there's something that throws SEYRpanel off and makes it think that the head placement is not on the Chuck/Target area. You get that error in the image above.

**Comment by bradmartin333** [comment]
@riversn Fixed yet?

**Comment by riversn** [comment]
This was a Xferprint demo bug, seems like a newer version of Xferprint fixed this issue, but haven't expressly tested.
