### ISSUE TITLE
SEYR Image Saver

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#129]
When wanting to take 100% images (using the '-1.00' box but setting it to "1.00" i.e. 100%) SEYR doesn't take RGB images and save them. If set to 100% it should always save an image, regardless of pass/fail. It doesn't save an image if every inspection area passes.

Might be something to do with the logic behind 'if there's nothing failing then it doesn't have to check for the save image routine?'

What worked is if I purposefully added a failing inspection box, then it would save images if the value was .99 or less.

A few updates though:

- Images need to be saved in a new folder, if you start and stop the run, don't overwrite the previous saved images. 
- Region fields should be separated into their own folder.
- Only A (Region Row/Col) fields are accurately getting named, B (fields) and C (Subfields) are not being updated with how they're being named, it's only 1,1,1,1 in the nameing, see image below.
- Chuck positions aren't needed in the name, could just use recipe name/folder name.

![image](https://user-images.githubusercontent.com/101815602/193648000-93403f26-6d7b-4e8e-a16a-469986122273.png)

**Comment by bradmartin333** [comment]
### Save Image Threshold
This code lies within the SEYR Control Panel. SEYR [currently returns image and ratio of failing features in the image to the host program](https://github.com/bradmartin333/SEYR/blob/f2266db7626173c4970c63f817be97a055f37195/SEYRproject/SEYR/ImageProcessing/BitmapFunctions.cs#L109). I believe if the numbox in the SEYR Control Panel is set to `0.00`, that would mean save every image. `-1.00` is a special override for the feature. `1.00` should save only if all features are passing and that might include the IMG feature. This is all based on my memory of the Host UI code. But, I believe you just need to set it to `0.00` and it should perform as desired.

### Save Image File System
Again, this is all within SEYR Control Panel. Seems like an easy feature request though 😉

**Comment by riversn** [comment]
If there's any inspection box passing, setting to 0.00 doesn't work

**Comment by bradmartin333** [comment]
I know there is a way to save all regardless, but I don't remember... I agree that the image saving UI needs an improvement though. An` off` / `save all` / `save if this % failing` drop down or something like that.

**Comment by riversn** [comment]
Seems you are correct, the only way to save all images regardless of pass fail is if there are no features at all (double.IsNaN(info )) and the numbox in the SEYR Panel (ImageSaveThreshold) = 0.
There could easily be an enum combo box sort of thing like I mentioned above.
And behold! The bug is clear! I forgot to replace X with Y (Shown in red).

____________________________________________________________________________________

Bitmap image = Cameras.SnapLiveImage().ToBitmap();
double info = await SEYRCh.NewImage(
    image, 
    Points[i].Callback, 
    ${i}\t{metroPos.X}\t{metroPos.Y}\t{Points[i]}", 
    stamp);
if ((ImageSaveThreshold != -1 && info > ImageSaveThreshold)
    || (double.IsNaN(info ) && ImageSaveThreshold == 0))
        image.Save
            ($"{SEYRCh.ImagesDirectory}" +
             $"{metroPos.X}_{metroPos.Y}" +
             $"_AX{Points[i].A.X + 1}_AY{Points[i].A.**X** + 1}" +
             $"_BX{Points[i].B.X + 1}_BY{Points[i].B.**X** + 1}" +
             $"_CX{Points[i].C.X + 1}_CY{Points[i].C.**X** + 1}.png");

____________________________________________________________________________________
