### ISSUE TITLE
Poor lighting differentiation between chip & background

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#130]
Low lighting sometimes seems to work best on some samples to differentiate between the chip being present and the background.

For instance, the chip and the background will both 'turn blue' (register as color entropy) at the same threshold values when a user can clearly see a difference still.

It's hard to describe the issue well, but the SEYR color analysis is sometimes able to differentiate between when it's plotting Blue vs Purple in the threshold map, but it'd be better if maybe the regions are separated a bit more somehow.

Very hard to send a sample image set for you to see what we mean.

**Comment by bradmartin333** [comment]
hard to know exactly what to test - it seems like the feature might have too many different possible states - meaning it is no longer "present" and "not present", but it is "empty" and "mostly empty". am I on the right track?

**Comment by bradmartin333** [comment]
okay - I made a simple but massive change

there is now a tool in the composer called "Entropy Balance" where you pick an RGB color

that color controls the levels of the image that go into the scoring routine:
default and legacy is always red (255, 0, 0).
if you make it black (0, 0, 0), you get no data.
if you make it white (255, 255, 255) you get a much smoother curve than legacy red.
you can make it any color in between (no transparency control, though)

**Comment by riversn** [comment]
Scroll bars for finetuning with default primary option buttons? (Red, Yellow, Blue, Green, etc..).
Need a way to test and compare when setting the recipe up.

**Comment by bradmartin333** [comment]
standard windows color picker

![image](https://github.com/bradmartin333/SEYR/assets/19335151/e958bba8-9192-4d04-b4f2-899c05dc63d3)

**Comment by riversn** [comment]
Yeah! That works!

**Comment by bradmartin333** [comment]
now the question... do you need one entropy balance per .seyr or one per feature?

**Comment by bradmartin333** [comment]
much better values with a bit more blue 
![image](https://github.com/bradmartin333/SEYR/assets/19335151/6b0c8486-1c9c-482a-8c25-3991edb1b033)

**Comment by bradmartin333** [comment]
click the chroma button to change color, then border color reflects it

**Comment by bradmartin333** [comment]
yes, but that reminds me I need to expose the default color so your team can change it in the XFER-SEYR panel

the exiting color is always Red, and that is the current default. But please test this in the demo .exe (new one coming soon)

**Comment by riversn** [comment]
For the color selector, is there a way to add an eyedropper so a user could click on a color on the screen to choose the color of the inspection chip? That could be really useful so they don't have to guess at the colors.

**Comment by bradmartin333** [comment]
yes, that is possible - but I am not sure you will want the chroma to be the color of the device itself. will know more after testing the newest demo .exe

**Comment by riversn** [comment]
Changing the chroma color setting **does not change** the threshold map image on the left. Wouldn't the image on the left change if the color that was being scanned for changed?

**Comment by riversn** [comment]
Chroma Setting is set to purple by default, can we change it back to whatever color it was originally by default? I thought it was Red (255, 0, 0).

**Comment by bradmartin333** [comment]
ya, that was not supposed to make it into the .exe, was just testing

**Comment by bradmartin333** [comment]
> Changing the chroma color setting **does not change** the threshold map image on the left. I feel like it should. Wouldn't the image on the left change if the color that was being scanned for changed?

ah, yeah, I cheat and don't actually use the scoring method to generate that image - it is kind of an estimation. I can update it, don't know how challenging/slow it will be

**Comment by riversn** [comment]
> ah, yeah, I cheat and don't actually use the scoring method to generate that image - it is kind of an estimation. I can update it, don't know how challenging/slow it will be

It's a must have, otherwise the user has no clue if they're capturing/scoring the chip, or capturing the background instead.

**Comment by bradmartin333** [comment]
ya - okay I got it to work and found a big error in the main calc as well

good news is that is looks really good with your sample pics and a gross color (111, 111, 0) with threshold 41

will make a new demo .exe with fixes

**Comment by riversn** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/101815602/f0d323fe-1c10-4419-8ac4-6f70bf1e1633)

threshold map does not match the score values being made. 

It's saying there's a valid chip but the map suggests the area should be null/missing

**Comment by riversn** [comment]
Vs this:

![image](https://github.com/bradmartin333/SEYR/assets/101815602/2e92b826-1b48-4280-85bb-8083c00ee23a)

**Comment by bradmartin333** [comment]
the opposite-ness is sort of an indicator of how the magic wand got there, but not exactly

current magic wand is `c = Color.FromArgb(Math.Min(255, c.R + c.B), Math.Min(255, c.G + c.B), 0);` but that is from limited testing

it is important to know that the threshold is only used for null detection, which will kick the score to -10

**Comment by riversn** [comment]
I think something is wrong with the yellow color, It's not displaying the threshold map correctly compared to the other colors

**Comment by bradmartin333** [comment]
there are 2 types of visualizations:
- threshold
- chroma
the final score is either chroma or -10, depending on the threshold

**Comment by bradmartin333** [comment]
The main reason for confusion is the current released version's `Threshold` button. It is a farce as has nothing to do with the final scoring. All it does it apply a 3rd party threshold function using the user's value on all channels - hence the hue that you see.

The new threshold button uses the very same calculations that are used at runtime. You get a greyscale image indicating the chroma image after the threshold is applied.

**Comment by riversn** [comment]
Sure, but the current display is incorrect...

The score values **are** correct, the map/image that's being displayed is not.

**Comment by riversn** [comment]
The map is showing an image that should be failing, but the scores are passing.

And it's only happening with yellow color

**Comment by bradmartin333** [comment]
hmm okay - I will isolate the functions and do some debugging. please continue to test the other additions as well as how the chroma performs regardless of the threshold preview. I have a lot of meetings today, so I will be slower.

**Comment by riversn** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/101815602/b91b4485-62e9-434c-9588-13067b9c45a8)

This should not be failing - there's a filled square, in the image, but a lot of white/unfilled space around it - enough to be more than 10%... so it should be a valid count. Idk, there's definitely something going on.

**Comment by bradmartin333** [comment]
yeah - I will figure it out... but the contrast looks much better! once I fix it, it should help a lot

**Comment by bradmartin333** [comment]
so weird - I am not seeing that issue... consistently getting scores of 20-40

**Comment by riversn** [comment]
> so weird - I am not seeing that issue... consistently getting scores of 20-40

Yes! That's part of the problem!

When it's unfilled, it's seeing a base score for some reason, it's like if there's unfilled there's noise. It should be failing it instead if the map is being displayed correctly.

**Comment by bradmartin333** [comment]
my bad - I meant consistent 20-40 scores where there is a chip

consistent -10 score for no chip

**Comment by bradmartin333** [comment]
maybe sched a teams call w/ me? idk if XDC is open to that
that way we can verify this stuff after I fix all the other new features and find bugs with this one

**Comment by bradmartin333** [comment]
took me a while to figure this out - but the duplicate ABC indices in the images dir mess up the image scroller

my guess is that the same grid was run with different origins for a total of 8 times? if not, then I am confused... so many coordinate systems...

anyway these chroma changes are looking good!

**Comment by bradmartin333** [comment]
[new demo here!!!](https://github.com/bradmartin333/SEYR/blob/d57e1f38585e85872efdbb7a1e71f89561758460/Setup/SEYRDesktopSetup.exe)

**Comment by riversn** [comment]
Okay, you gotta explain what the different colors in the map now mean.

![image](https://github.com/bradmartin333/SEYR/assets/101815602/ab9ae5fd-0e44-4813-8c3d-04a0d8847b0b)

**Comment by riversn** [comment]
Something is off with the color Green:

It's like green doesn't get counted for any score values.
![image](https://github.com/bradmartin333/SEYR/assets/101815602/11bddc8b-91e7-4bef-ba43-441e7c97fc8f)

**Comment by riversn** [comment]
When I land on a decent color, I get such better separation now!

Super cool to see!
![image](https://github.com/bradmartin333/SEYR/assets/101815602/0ad97cd0-b6d8-4311-9713-7a7ec7b195eb)

**Comment by bradmartin333** [comment]
Any issues or it just needs some documentation?

**Comment by riversn** [comment]
Dark green is messed up 
![image](https://github.com/bradmartin333/SEYR/assets/101815602/c3b6d67d-d771-42b0-ad39-21119e9a1af1)

**Comment by bradmartin333** [comment]
this is the logarithmic linear color space of one of the brighter pics from GIMP 

![image](https://github.com/bradmartin333/SEYR/assets/19335151/bf2ddad6-161d-406c-8c78-ec06a5bde8b3)

the color you select is [**like** a chroma key](https://en.wikipedia.org/wiki/Chroma_key), but not exactly. you select a color distribution to emphasize in the image pre-threshold. For these images, a bright yellow (255, 255, 0) looks pretty good at the lows and highs and will likely mask out most of the blurry blue blackground.

**Comment by bradmartin333** [comment]
it might be best to restrict chroma to a third of the color wheel (> 300 deg or < 60 deg)

![image](https://github.com/bradmartin333/SEYR/assets/19335151/bf5198fe-bee0-46c0-85b9-db137806632b)

**Comment by riversn** [comment]
I liked the magic wand button, kinda sad it went away

**Comment by riversn** [comment]
If user selects Red chroma (same as default, but actually selecting it) it should fill red to show, not same as background like default does
![image](https://github.com/bradmartin333/SEYR/assets/101815602/e4001e0b-3bfc-4310-9e4a-fa576e6818f7)

**Comment by bradmartin333** [comment]
I'm thinking I will create a new wizard window with a teaser v1.4 format that will replace the chroma button and threshold slider as well as show the steps it takes to get the score. Might take a bit longer, so let me know if you'd rather I just make documentation about what it does. I can do the manual red thing, but it will mean an additional serialized boolean for each feature.

**Comment by riversn** [comment]
Whatever doesn't cause issues with performance probably.

I actually like the chroma button a lot - as it stand it really does work really well. Maybe the magic wand button could be replaced with a wizard hat and that could open the 'color wizard'. But leaving the chroma button as is.

**Comment by riversn** [comment]
I've got great pass/fail results with v1.3.28

White/Grey/DarkGrey, and for other samples, gold/orange, and light green, purple/blue, and red all have good/interesting results.

I do need a definition of what the color and scoring means. 
In the threshold map:

- black = empty
- white (and any color except purple or green?) = filled.

But fundamentally, this works amazingly well! I really can't be more excited with it in how much it helps improve yield fidelity.

**Comment by bradmartin333** [comment]
ok - I will create a graphic showing how it works

**Comment by bradmartin333** [comment]
infographic added to readme
