### ISSUE TITLE
Select & change Multiple features

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#134]
When changing a ton of feature criteria, would be great if you can select and change all their threshold values together, or delete them all at once.

![image](https://github.com/bradmartin333/SEYR/assets/101815602/ae781902-4400-4986-9a5b-11b66d0f0a26)

**Comment by bradmartin333** [comment]
how about when more than one is selected, clicking the threshold button sets them all to the clicked button's value? and the delete button would multi-delete. also, any selected feature would be deselected.

**Comment by riversn** [comment]
No, clicking the top threshold button is no good because we click the threshold buttons to test and compare between different features. It'd be too easy to accidentally overwrite other values. And there's no Ctrl-Z undo functions, which is you may want to add!

**Comment by riversn** [comment]
Another alternative/parallels idea is to copy/paste the parameters of one feature to another. Like, ctrl+C one highlighed, and paste to the rest highlighted.

If you paste and nothing is highlighted, then it just makes a duplicate

**Comment by riversn** [comment]
The purple highlighting is actually annoying, the thicker/darker outline at the top and bottom is too much. I'm not sure what the correct behavior should look like, but there's just something wrong with it currently
![image](https://github.com/bradmartin333/SEYR/assets/101815602/d407fddd-fc48-4fda-99ac-c8c86fd084df)

**Comment by bradmartin333** [comment]
okay - can do - I literally copied and pasted the example format lol

**Comment by bradmartin333** [comment]
hmm... actually it seems the only thing that works is border changes... I will try to make it less harsh I suppose

**Comment by riversn** [comment]
Can you just get rid of the hover-over color highlighting? It wasn't there before

**Comment by riversn** [comment]
I want to right click 1 feature, select copy (or ctrl+C when highlighted) and then select multiple features and paste that copied 'threshold format' to overwrite all the threshold values.

Right click -> Past,  should have two separate options, paste only threshold & chroma color & Null features (i.e. threshold format) or 'paste all values' which would paste the everything above including shape width and height, but **NOT** changing the position.

that workflow is a tad different than the current implementation.

**Comment by bradmartin333** [comment]
sounds like a shortcut to replace cloning and repositioning? I can add the null features to the right click menu

**Comment by bradmartin333** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/19335151/11b681b1-68e2-495b-9c83-7aaf6999c25c)
