### ISSUE TITLE
Running diagnostic stats for features

### ISSUE THREAD

**Issue by bradmartin333** [bradmartin333/SEYR#136]
> As SEYR runs it'd be great to display a small distribution chart of the current run so the user can see how inspection units are being scored. Right now, if the user wants to check if the threshold works real well, they have to run the seyr recipe, stop it, parse it with xfersuite, and then check the distribution of the scores to see if there's good separation. Would be great to see a simplified version as it runs maybe?

**Comment by bradmartin333** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/19335151/b7a674ed-51e9-4377-bb85-ca552a89c6d9)

**Comment by bradmartin333** [comment]
with Red Chroma:
![image](https://github.com/bradmartin333/SEYR/assets/19335151/7e4295db-eb6c-42be-bfb9-ccb7f5e6dd71)

with Adjusted Chroma:
![image](https://github.com/bradmartin333/SEYR/assets/19335151/ea910ffe-4495-4aa8-b871-cdf395659dcb)

**Comment by riversn** [comment]
That's cool, but it looks like it's within the composer. Is it being displayed while a seyr is running? If user changes threshold/color settings it should reset previous scores so they aren't all combined in.

**Comment by bradmartin333** [comment]
I will make sure that the scores reset on threshold/chroma change

It is not being displayed while seyr is running because I am using the existing "select a feature" UI in the composer. if you really really need it to show while running - it will likely expand the viewer window or be a new window

**Comment by bradmartin333** [comment]
and an additional selector for which feature you are observing?

**Comment by riversn** [comment]
> and an additional selector for which feature you are observing?

Yep!

**Comment by riversn** [comment]
If user selects the chip at the end of the run, the distribution data gets wiped - I'd like it to stay up so you can evaluate it

![image](https://github.com/bradmartin333/SEYR/assets/101815602/16c906c9-2cdf-40f7-bd84-9787aacff865)

Also, can we change the axis to it plots on the X axis instead of Y? (left and right not up/down)

**Comment by bradmartin333** [comment]
it will definitely become a memory issue, so nvm I will make the default 1000 and allow for a max of, say, 10000

**Comment by riversn** [comment]
What's null count mean?
![image](https://github.com/bradmartin333/SEYR/assets/101815602/e784c69f-f9e4-48bc-beda-de1b8acdf486)

**Comment by bradmartin333** [comment]
null = score of -10 = same null from composer

**Comment by riversn** [comment]
Can we put the null count to the side instead of in the title position?

Also rename it to 'Failing Null count' so it's clearer what it's describing.

**Comment by riversn** [comment]
Window behavior is also a tad wonky, when the distribution plot is open, it should take up a minimum space, but when the viewer window is enlarged, the viewer part should take up more of the window as a percentage. Right now it's always 50/50. That's fine when the window is small, but when the window is larger, the viewer screen should be more like 75/25.

![image](https://github.com/bradmartin333/SEYR/assets/101815602/d2fd0f07-0062-425a-b023-5e77c4af4483)

**Comment by bradmartin333** [comment]
okay - I will cleanup the plots and make the plot fixed px size

**Comment by bradmartin333** [comment]
default is 1000, theoretical max is 2,147,483,647 (int.max)

**Comment by riversn** [comment]
Bottom graph doesn't do anything now - just plots 1 bar with no axis or any info... it's weird
![image](https://github.com/bradmartin333/SEYR/assets/101815602/764c28aa-dd8b-4371-855b-dbcce0a6e062)

**Comment by riversn** [comment]
nvm the drop down was blank/unselected. That's the issue. Can we default it to the first criteria instead of nothing?

**Comment by riversn** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/101815602/88cce39e-ca47-4a57-8105-f6e625e317d8)

When clicking on a bar - can it overlay the row/col/subrow/col info so the user can go back and look at that specific index?

**Comment by riversn** [comment]
Can we increase the number of axis ticks for more values across the entire range.
Also feather the min and max a tad - go past the min axis value and past the max one a bit to not have the bars on the edge of the graph

![image](https://github.com/bradmartin333/SEYR/assets/101815602/62467d1c-8c54-4ac7-9958-44b810925d96)

**Comment by bradmartin333** [comment]
i can do all of that besides clicking the bar - it would be a ton of overhead and would definitely kill performance to the point where you would have to stop the run (XferSuite is well suited for that)

if you really need it, make a new issue and it can be a v1.4 item

**Comment by riversn** [comment]
> clicking the bar - it would be a ton of overhead and would definitely kill performance to the point where you would have to stop the run (XferSuite is well suited for that). if you really need it, make a new issue and it can be a v1.4 item

We can live without it. The plot itself is actually really decent as is, don't bang your head on it!

**Comment by bradmartin333** [comment]
okay, I think I got everything but clicking bars in

**Comment by riversn** [comment]
This is awesome!
![image](https://github.com/bradmartin333/SEYR/assets/101815602/fdc10f91-1143-4e86-8b3a-8af24660c1eb)
It's great
