### ISSUE TITLE
Threshold number box not changing

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#140]
using the down button on the number box for the threshold box doesn't change/update the threshold value. Clicking on the slider does.

![image](https://github.com/bradmartin333/SEYR/assets/101815602/a0b7266e-7611-490c-b0ac-2a84b691b68d)

**Comment by riversn** [comment]
Sometimes left clicking on the slider to move threshold, the slider DOES move, but the number value doesn't change. (it's as if it moves in 0.5 steps instead of full 1 values)
![image](https://github.com/bradmartin333/SEYR/assets/101815602/389a63d8-d6ce-47ee-b0aa-e9c87c80c6b6)

**Comment by bradmartin333** [comment]
changed large change to be 5, small change still 1

added some logic to prevent infinite looping

note that you can use pgup/pgdown for large change and arrow keys for small change
