### ISSUE TITLE
Add Score callout for feature

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#142]
Can we show the score for the corresponding highlighted feature criteria under the image viewer?

![image](https://github.com/bradmartin333/SEYR/assets/101815602/317e7c45-2ef1-457e-a48f-7fc561461e20)

**Comment by bradmartin333** [comment]
I can add a label for the current feature's score - but it would be tricky to have multiple shown and have the information be accurate without regularly updating all the scores (making things laggy, at least in v1.3)

**Comment by riversn** [comment]
Oh, if performance is an issue, then we probably don't want it - maybe only the one that is highlighted on the left and in the table on the right.

**Comment by bradmartin333** [comment]
having all that info available would be nice though, and I will keep it in mind if v1.4 is ever 🟢

**Comment by bradmartin333** [comment]
![image](https://github.com/bradmartin333/SEYR/assets/19335151/2897b448-a67f-4fe1-8e0a-db09b009be93)
