### ISSUE TITLE
Add ObjectListView.Updated to project

### ISSUE THREAD

**Issue by StevenKelleher** [bradmartin333/SEYR#143]
Hey Brad,

Can you please add ObjectListView.Updated to the SEYR References.
No need to remove ObjectListView.Official.

We have add ObjectListView.Updated to XferPrint and we need it added here for it to work.

Steven

**Comment by bradmartin333** [comment]
good thing I have the same phone number! nuget was giving me auth issues.

just pushed the v1.3.31 nuget package with ObjectListView.Updated as a dependency

i will keep this issue open in case it doesn't work

**Comment by StevenKelleher** [comment]
Thanks Brad.
Ya that worked.
Steven
