### ISSUE TITLE
Array Copy/array size applies to all arrays, not individual ones

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#38]
Creating an rectangle field and changing copy/array size, changes the copy parameters for every future array created.

I want to be able to make a separate 2x2 array, and a 6x6 array at the same time, but can't do that.

https://user-images.githubusercontent.com/101815602/158868435-c7b61b4f-a0c9-4a82-ace6-71a086e2f152.mp4

**Comment by bradmartin333** [comment]
This is the intended behavior, but can discuss further

**Comment by bradmartin333** [comment]
So, why would this ever be necessary?

**Comment by riversn** [comment]
![image](https://user-images.githubusercontent.com/101815602/159008966-c7b885fa-3ce4-40c4-9ae3-2919d50dbd1e.png)

**Comment by bradmartin333** [comment]
you can score a tile based on it's features (what you're calling subunits), so there is no need for an encompassing, larger feature. having unused data is okay.
