### ISSUE TITLE
Selected Row/col can be over maximum

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#75]
Disallow selected row/col to be indexed further than max

![image](https://user-images.githubusercontent.com/101815602/165314146-e4c9572e-2215-4f1d-a632-e1628a680aaa.png)

**Comment by bradmartin333** [comment]
this is actually intentional so you can have a "feature only" view of your setup... adding the constraint is possible, but also bug prone. does it need the constraint?

**Comment by bradmartin333** [comment]
Looked into this - it is actually providing a valid image of null pixels because it's location is off the loaded image
