### ISSUE TITLE
feature grid pitch

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#92]
Feature grid pitch is not as fine as I would like, there's a couple issues mixed in here. The crux is that the grid pitches + feature box size just isn't always the right number. As in, almost every time with a grid array larger than 4x4, a pitch of 12.5px instead of 12 or 13px, would work better because it's just slightly off the mark.

This causes the edge row/columns to be off and the user has no way to adjust the grid to make it fit better.

I don't know if this is because of the slight optical changes in the optics as you move to the edge of the viewing area or if it's something else just not adding up nicely.

The second issue stems from if the user doesn't make the correct optical choice and starts a seyr run. For instance, if the optic is a 5x but Xferprint was still set to 20x settings. sure the numbers for px/um don't add up correctly, but the bigger issue is that the changes in values is drastically different. Like the spacing for grid values is way larger than what we want. 
So - when you go back and set the correct settings, the SEYR report is already made and you can't changes this to where is would be better with the correct 5x settings. Maybe a tool -> drop down -> reset xferprint data or repull setupdata option might work for this case. The current fix is to open an new project directory or delete the SEYR report and make a fresh one.

**Comment by bradmartin333** [comment]
- If half pitches are the issue, the only way to resolve that is by changing the image scaling %
- The currently loaded HiMag Cal Space (5x, 10x...) is reloaded when SEYR is started up - so if the correct calibration space is loaded in XferPrint, the correct PxToMicron value will be passed to SEYR. If that value is not perfect, it can be recalibrated via Cognex.
- If the solution would be to give access to that parameter within SEYR, I can arrange for that - but yes, it will mess up your already created grid and features

**Comment by riversn** [comment]
I should have made a video of it

**Comment by bradmartin333** [comment]
In any case, you cannot draw a pixel where there is none - but yes, a video would help

**Comment by bradmartin333** [comment]
added in XFER-912
