### ISSUE TITLE
rotational alignment

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#94]
Is there a way to tell the tool which chuck position we're looking at to inspect?

Like for rotational alignment, does it always default to target rotation right now? What If I want to inspect source or cleaning pad and their rotation is different? Is this handled by xferprint and if it was a post-pick/post-print metro stop it would take the correct target vs stamp vs source rotation info?

**Comment by bradmartin333** [comment]
Currently, you would only be able to run on Source and Target chucks as they are the only ones with A B positions. Then yes, those A B positions are used to correct for rotation.

**Comment by riversn** [comment]
How can I tell the tool to use source or use target alignment rotations?

**Comment by bradmartin333** [comment]
It knows the same way the vision settings load

**Comment by bradmartin333** [comment]
would you rather have everything be manual via the SEYR control panel?

**Comment by riversn** [comment]
If I put the inspection thing on the source chuck, do source A -B on it, then setup something on the target chuck, then go and try to inspect the source chuck thing, how do I know if the tool is set to the rotation of the target or the source?  because it could be one or the other right?
