### ISSUE TITLE
Composer font size

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#98]
Images of grid/feature criteria scale nicely with window size, text does not.

When window gets larger, scale text to make it larger too - I was showing other users the screen and tried to make it more readable for people who were farther away but the text stays small so I can't.

**Comment by bradmartin333** [comment]
hmm, this is interesting - would probably have to convert the form to WPF - don't know if Winforms can really handle that

**Comment by bradmartin333** [comment]
try changing the scaling % for the display?

**Comment by bradmartin333** [comment]
this would mean wiring in a font to every control and winforms might break with this

**Comment by bradmartin333** [comment]
make some fonts bigger
